version: "3.8"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
  postgres:
    image: postgres:15.2-alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
